### ISSUE TITLE
Shock ID not given by VirSorter in Kbase

### ISSUE THREAD

**Issue by jamesck2** [WrightonLabCSU/kb_DRAM#3]
I am trying to use DRAM-v in Kbase, and I know that I am supposed to look in the results summary of my VirSorter run in Kbase for the shock ID of the .tab file for DRAM-v, however, this is absent from my VirSorter outputs unlike the example shown in the last issue. I hope this is the right place to ask. Thank you in advance.
<img width="2086" alt="Screen Shot 2022-01-25 at 12 52 03 PM" src="https://user-images.githubusercontent.com/68616716/151040259-2e1f767c-af40-474c-9a9e-0aed4259a7e7.png">

**Comment by rmFlynn** [comment]
It looks like there was a problem in virsorter while the developer moved the shock ID to the Summary. If you remove and add the virsorter modal back and run again, you will find the shock ID in the Summary.
